name: HexiTrade
main: com.hexicraft.trade.Main
version: 1.0
description: A trading plugin that varies the price of items depending on their demand.
depend: [Vault]
commands:
    trade:
        description: Gives information on the trading plugin.
        usage: /trade
        permission: hexitrade.user
        permission-message: You don't have permission to do this.
        aliases: [hexitrade, ht]
    sell:
        description: Sells the item in your hand
        usage: /sell
        permission: hexitrade.user
        permission-message: You don't have permission to do this.
    price:
        description: Gives the price of the item in your hand
        usage: /price
        permission: hexitrade.user
        permission-message: You don't have permission to do this.
        aliases: [value, worth]
    buy:
        description: Opens up the buy interface
        usage: /buy
        permission: hexitrade.user
        permission-message: You don't have permission to do this.
        aliases: []