name: HexiTrade
main: com.hexicraft.trade.HexiTrade
version: 1.1
description: A trading plugin that varies the price of items depending on their demand.
softdepend: [Vault, Essentials]
commands:
  trade:
    description: Gives information about HexiTrade.
    usage: /trade [arg]
    permission: hexitrade.user
    permission-message: You don't have permission to do this.
    aliases: [hexitrade, ht]
  sell:
    description: Sells an item
    usage: /sell [item] [amount]
    permission: hexitrade.user
    permission-message: You don't have permission to do this.
  buy:
    description: Opens the buy interface or buys an item
    usage: /buy [item] [amount]
    permission: hexitrade.user
    permission-message: You don't have permission to do this.
  worth:
    description: Gives the sell worth of an item
    usage: /worth [item] [amount]
    permission: hexitrade.user
    permission-message: You don't have permission to do this.
  price:
    description: Gives the buy price of an item
    usage: /price [item] [amount]
    permission: hexitrade.user
    permission-message: You don't have permission to do this.